
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector: { app: auth-service }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
