
version: "3.8"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports: ["3306:3306"]
    volumes: ["mysqldata:/var/lib/mysql"]

  auth-service:
    build: ./auth_service
    environment:
      PORT: 8081
      JWT_SECRET: "change-me"
    ports: ["8081:8081"]
    depends_on: ["mysql"]

  etl:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./etl:/app
    command: ["python", "run_etl.py"]
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: appdb
    depends_on: ["mysql"]

volumes:
  mysqldata:
