replicaCount: 2

image:
  repository: docker.io/ashish030202/payment-service-backend
  tag: "0.1.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}
  
autoscaling:
   enabled: false          # set true when you actually want HPA
   minReplicas: 2
   maxReplicas: 5
   targetCPUUtilizationPercentage: 70
   targetMemoryUtilizationPercentage: 80


service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://payment-mysql:3306/paymentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom: { secretKeyRef: { name: payment-db-secret, key: username } }
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom: { secretKeyRef: { name: payment-db-secret, key: password } }
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_PROFILES_ACTIVE
    value: "staging"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.shop.local
      paths:
        - path: /
          pathType: Prefix
